name: GroupsUI
main: ChampOfGames\GroupsUI\Main
authors:
  - ChampOfGames
  - Tatsomi
version: 1.0.1
api: 5.0.0

commands:
  groupsui:
    permission: groupsui.cmd
    description: Manage Groups with an UI
permissions:
  groupsui.cmd:
    default: op
