name: GroupsUI
main: ChampOfGames\GroupsUI\Main
author: ChampOfGames
# converted by Tatsomi https://github.com/Tatsomi
version: 1.0.2
api: 5.0.0

commands:
  groupsui:
    permission: groupsui.cmd
    description: Manage Groups with an UI
permissions:
  groupsui.cmd:
    default: op
